export const COUNTRIES_DATA: Record<string, Record<string, string[]>> = {
  India: {
    "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Hyderabad", "Nellore", "Tirupati", "Guntur", "Anantapur"],
    "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Pasighat", "Tezu", "Aalo", "Tawang"],
    "Assam": ["Guwahati", "Nagaon", "Silchar", "Barpeta", "Udalguri", "Kamrup", "Goalpara"],
    "Bihar": ["Patna", "Gaya", "Bhagalpur", "Munger", "Darbhanga", "Muzaffarpur", "Buxar"],
    "Chhattisgarh": ["Raipur", "Bilaspur", "Durg", "Rajnandgaon", "Raigarh", "Jagdalpur"],
    "Goa": ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda"],
    "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Jamnagar", "Bhavnagar", "Gandhinagar"],
    "Haryana": ["Faridabad", "Gurgaon", "Hisar", "Rohtak", "Panipat", "Karnal", "Yamunanagar"],
    "Himachal Pradesh": ["Shimla", "Solan", "Mandi", "Kangra", "Hamirpur", "Kullu"],
    "Jharkhand": ["Ranchi", "Dhanbad", "Giridih", "Jamshedpur", "Hazaribag", "East Singhbhum"],
    "Karnataka": ["Bangalore", "Hubli", "Mysore", "Belgaum", "Mangalore", "Gulbarga", "Davangere"],
    "Kerala": ["Kochi", "Thiruvananthapuram", "Kozhikode", "Thrissur", "Alappuzha", "Kannur"],
    "Madhya Pradesh": ["Indore", "Bhopal", "Jabalpur", "Gwalior", "Ujjain", "Saguor", "Rewa"],
    "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Thane", "Aurangabad", "Nashik", "Kolhapur"],
    "Manipur": ["Imphal", "Thoubal", "Bishnupur", "Churachandpur", "Senapati"],
    "Meghalaya": ["Shillong", "Tura", "Jowai", "Nongstoin", "Goalpara"],
    "Mizoram": ["Aizawl", "Lunglei", "Saiha", "Champhai", "Kolasib"],
    "Nagaland": ["Kohima", "Dimapur", "Wokha", "Tuensang", "Mon"],
    "Odisha": ["Bhubaneswar", "Cuttack", "Sambalpur", "Rourkela", "Balasore", "Berhampur"],
    "Punjab": ["Ludhiana", "Amritsar", "Chandigarh", "Patiala", "Jalandhar", "Bathinda"],
    "Rajasthan": ["Jaipur", "Jodhpur", "Kota", "Ajmer", "Bikaner", "Udaipur", "Alwar"],
    "Sikkim": ["Gangtok", "Namchi", "Mangan", "Gyalshing", "Rangpo"],
    "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Salem", "Trichy", "Tirunelveli"],
    "Telangana": ["Hyderabad", "Secunderabad", "Warangal", "Nizamabad", "Karimnagar"],
    "Tripura": ["Agartala", "Udaipur", "Dharmanagar", "Ambassa", "Kailasahar"],
    "Uttar Pradesh": ["Lucknow", "Kanpur", "Varanasi", "Ghaziabad", "Noida", "Agra", "Meerut"],
    "Uttarakhand": ["Dehradun", "Haridwar", "Nainital", "Almora", "Rudraprayag", "Pithoragarh"],
    "West Bengal": ["Kolkata", "Asansol", "Siliguri", "Durgapur", "Darjeeling", "Howrah"],
    "Andaman & Nicobar": ["Port Blair", "Car Nicobar", "Little Andaman"],
    "Chandigarh": ["Chandigarh"],
    "Dadra & Nagar Haveli": ["Silvassa", "Dadra", "Khanvel"],
    "Daman & Diu": ["Daman", "Diu", "Khor"],
    "Delhi": ["New Delhi", "North Delhi", "South Delhi", "East Delhi", "West Delhi"],
    "Lakshadweep": ["Kavaratti", "Andrott", "Agatti"],
    "Puducherry": ["Puducherry", "Yanam", "Karaikal", "Mahe"],
    "Ladakh": ["Leh", "Kargil", "Nyoma", "Diskit"],
  },
  "United States": {
    "Alabama": ["Birmingham", "Montgomery", "Mobile", "Huntsville", "Tuscaloosa"],
    "Alaska": ["Anchorage", "Fairbanks", "Juneau", "Sitka"],
    "Arizona": ["Phoenix", "Mesa", "Chandler", "Scottsdale", "Glendale"],
    "Arkansas": ["Little Rock", "Fayetteville", "Springdale", "Jonesboro"],
    "California": ["Los Angeles", "San Francisco", "San Diego", "Sacramento", "San Jose"],
    "Colorado": ["Denver", "Aurora", "Colorado Springs", "Fort Collins"],
    "Connecticut": ["Bridgeport", "New Haven", "Hartford", "Stamford"],
    "Delaware": ["Wilmington", "Dover", "Newark", "Middletown"],
    "Florida": ["Jacksonville", "Miami", "Tampa", "Orlando", "Tallahassee"],
    "Georgia": ["Atlanta", "Augusta", "Savannah", "Columbus"],
    "Hawaii": ["Honolulu", "Hilo", "Kailua", "Wailuku"],
    "Idaho": ["Boise", "Meridian", "Pocatello", "Idaho Falls"],
    "Illinois": ["Chicago", "Aurora", "Rockford", "Joliet", "Springfield"],
    "Indiana": ["Indianapolis", "Fort Wayne", "Evansville", "South Bend"],
    "Iowa": ["Des Moines", "Cedar Rapids", "Davenport", "Iowa City"],
    "Kansas": ["Kansas City", "Wichita", "Topeka", "Overland Park"],
    "Kentucky": ["Louisville", "Lexington", "Bowling Green", "Covington"],
    "Louisiana": ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette"],
    "Maine": ["Portland", "Lewiston", "Augusta", "Bangor"],
    "Maryland": ["Baltimore", "Frederick", "Gaithersburg", "Rockville"],
    "Massachusetts": ["Boston", "Worcester", "Springfield", "Lowell"],
    "Michigan": ["Detroit", "Grand Rapids", "Warren", "Sterling Heights"],
    "Minnesota": ["Minneapolis", "Saint Paul", "Rochester", "Bloomington"],
    "Mississippi": ["Jackson", "Gulfport", "Biloxi", "Greenville"],
    "Missouri": ["Kansas City", "Saint Louis", "Springfield", "Independence"],
    "Montana": ["Billings", "Missoula", "Great Falls", "Butte"],
    "Nebraska": ["Omaha", "Lincoln", "Bellevue", "Grand Island"],
    "Nevada": ["Las Vegas", "Henderson", "Reno", "Paradise"],
    "New Hampshire": ["Manchester", "Nashua", "Concord", "Derry"],
    "New Jersey": ["Newark", "Jersey City", "Paterson", "Elizabeth"],
    "New Mexico": ["Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe"],
    "New York": ["New York", "Buffalo", "Rochester", "Yonkers"],
    "North Carolina": ["Charlotte", "Raleigh", "Greensboro", "Winston-Salem"],
    "North Dakota": ["Bismarck", "Fargo", "Grand Forks", "Minot"],
    "Ohio": ["Columbus", "Cleveland", "Cincinnati", "Toledo"],
    "Oklahoma": ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow"],
    "Oregon": ["Portland", "Eugene", "Salem", "Gresham"],
    "Pennsylvania": ["Philadelphia", "Pittsburgh", "Allentown", "Erie"],
    "Rhode Island": ["Providence", "Warwick", "Cranston", "Pawtucket"],
    "South Carolina": ["Charleston", "Columbia", "Greenville", "Spartanburg"],
    "South Dakota": ["Sioux Falls", "Rapid City", "Aberdeen", "Watertown"],
    "Tennessee": ["Memphis", "Nashville", "Knoxville", "Chattanooga"],
    "Texas": ["Houston", "Dallas", "Austin", "San Antonio"],
    "Utah": ["Salt Lake City", "West Valley City", "Provo", "Orem"],
    "Vermont": ["Burlington", "Rutland", "South Burlington", "Barre"],
    "Virginia": ["Virginia Beach", "Richmond", "Arlington", "Alexandria"],
    "Washington": ["Seattle", "Spokane", "Tacoma", "Vancouver"],
    "West Virginia": ["Charleston", "Huntington", "Parkersburg", "Wheeling"],
    "Wisconsin": ["Milwaukee", "Madison", "Green Bay", "Kenosha"],
    "Wyoming": ["Cheyenne", "Casper", "Laramie", "Gillette"],
  },
  Canada: {
    Alberta: ["Calgary", "Edmonton", "Red Deer", "Lethbridge"],
    "British Columbia": ["Vancouver", "Victoria", "Surrey", "Burnaby"],
    Manitoba: ["Winnipeg", "Brandon", "Missoula", "Flin Flon"],
    "New Brunswick": ["Saint John", "Moncton", "Fredericton", "Bathurst"],
    "Newfoundland and Labrador": ["St. John's", "Corner Brook", "Gander", "Labrador City"],
    "Northwest Territories": ["Yellowknife", "Hay River", "Inuvik", "Tuktoyaktuk"],
    "Nova Scotia": ["Halifax", "Cape Breton", "Dartmouth", "Glace Bay"],
    Nunavut: ["Iqaluit", "Rankin Inlet", "Arviat", "Qikiqtarjuaq"],
    Ontario: ["Toronto", "Ottawa", "Hamilton", "London"],
    "Prince Edward Island": ["Charlottetown", "Summerside", "Stratford", "Cornwall"],
    Quebec: ["Montreal", "Quebec City", "Laval", "Gatineau"],
    Saskatchewan: ["Saskatoon", "Regina", "Prince Albert", "Moose Jaw"],
    Yukon: ["Whitehorse", "Dawson City", "Watson Lake", "Haines Junction"],
  },
  "United Kingdom": {
    England: ["London", "Manchester", "Birmingham", "Leeds", "Liverpool", "Bristol", "Sheffield"],
    Scotland: ["Edinburgh", "Glasgow", "Aberdeen", "Dundee", "Stirling"],
    Wales: ["Cardiff", "Swansea", "Newport", "Bangor"],
    "Northern Ireland": ["Belfast", "Derry", "Armagh", "Lisburn"],
  },
  Australia: {
    "New South Wales": ["Sydney", "Newcastle", "Wollongong", "Canberra", "Armidale"],
    Queensland: ["Brisbane", "Gold Coast", "Sunshine Coast", "Cairns", "Townsville"],
    "South Australia": ["Adelaide", "Port Augusta", "Mount Gambier", "Whyalla"],
    Tasmania: ["Hobart", "Launceston", "Devonport", "Burnie"],
    Victoria: ["Melbourne", "Geelong", "Ballarat", "Bendigo"],
    "Western Australia": ["Perth", "Fremantle", "Mandurah", "Bunbury"],
    "Australian Capital Territory": ["Canberra"],
    "Northern Territory": ["Darwin", "Alice Springs", "Palmerston"],
  },
  Pakistan: {
    Balochistan: ["Quetta", "Gwadar", "Chaman", "Sibi"],
    "Federal Capital": ["Islamabad", "Rawalpindi"],
    "Khyber Pakhtunkhwa": ["Peshawar", "Mardan", "Abbottabad", "Swat"],
    Punjab: ["Lahore", "Karachi", "Faisalabad", "Multan"],
    Sindh: ["Karachi", "Hyderabad", "Larkana", "Sukkur"],
    "Gilgit-Baltistan": ["Gilgit", "Skardu", "Hunza"],
    "Azad Jammu & Kashmir": ["Muzaffarabad", "Mirpur", "Rawalakot"],
  },
  Bangladesh: {
    Dhaka: ["Dhaka", "Narayanganj", "Gazipur", "Tangail"],
    Chittagong: ["Chittagong", "Comilla", "Sylhet", "Khulna"],
    Rajshahi: ["Rajshahi", "Pabna", "Bogra", "Dinajpur"],
    Khulna: ["Khulna", "Barisal", "Pirojpur", "Jhalokathi"],
    Barisal: ["Barisal", "Patuakhali", "Bhola"],
    Rangpur: ["Rangpur", "Thakurgaon", "Nilphamari"],
    Mymensingh: ["Mymensingh", "Sherpur", "Jamalpur"],
  },
  Brazil: {
    "São Paulo": ["São Paulo", "Campinas", "Santos"],
    "Rio de Janeiro": ["Rio de Janeiro", "Niterói", "Duque de Caxias"],
    "Minas Gerais": ["Belo Horizonte", "Uberlândia", "Contagem"],
    Bahia: ["Salvador", "Feira de Santana", "Vitória da Conquista"],
    Pará: ["Belém", "Ananindeua", "Parauapebas"],
    "Rio Grande do Sul": ["Porto Alegre", "Caxias do Sul", "Pelotas"],
    Ceará: ["Fortaleza", "Caucaia", "Juazeiro do Norte"],
    Pernambuco: ["Recife", "Jaboatão dos Guararapes", "Caruaru"],
    Paraná: ["Curitiba", "Londrina", "Maringá"],
    Goiás: ["Goiânia", "Anápolis", "Rio Verde"],
  },
  Germany: {
    "Baden-Württemberg": ["Stuttgart", "Mannheim", "Karlsruhe", "Heidelberg"],
    Bavaria: ["Munich", "Nuremberg", "Augsburg", "Regensburg"],
    Berlin: ["Berlin"],
    Brandenburg: ["Potsdam", "Frankfurt (Oder)", "Cottbus"],
    Bremen: ["Bremen", "Bremerhaven"],
    Hamburg: ["Hamburg"],
    Hesse: ["Frankfurt", "Wiesbaden", "Darmstadt"],
    "Lower Saxony": ["Hanover", "Braunschweig", "Oldenburg"],
    "North Rhine-Westphalia": ["Cologne", "Düsseldorf", "Dortmund"],
  },
  France: {
    "Île-de-France": ["Paris", "Versailles", "Boulogne-Billancourt"],
    "Provence-Alpes-Côte d'Azur": ["Marseille", "Nice", "Cannes"],
    "Auvergne-Rhône-Alpes": ["Lyon", "Grenoble", "Saint-Étienne"],
    "Nouvelle-Aquitaine": ["Bordeaux", "Limoges", "Poitiers"],
    Normandy: ["Rouen", "Caen", "Le Havre"],
    Brittany: ["Rennes", "Nantes", "Brest"],
  },
  Japan: {
    Hokkaido: ["Sapporo", "Asahikawa", "Hakodate"],
    Tokyo: ["Tokyo", "Shinjuku", "Shibuya"],
    Osaka: ["Osaka", "Kobe", "Sakai"],
    Kyoto: ["Kyoto"],
    Nagoya: ["Nagoya"],
    Yokohama: ["Yokohama"],
    Kawasaki: ["Kawasaki"],
  },
  Mexico: {
    "Mexico City": ["Mexico City", "Azcapotzalco", "Coyoacán"],
    "State of Mexico": ["Ecatepec", "Naucalpán", "Tlalnepantla"],
    Jalisco: ["Guadalajara", "Zapopan", "Tlaquepaque"],
    Veracruz: ["Veracruz", "Xalapa", "Córdoba"],
    Puebla: ["Puebla", "Ecatepec", "Tlaxcala"],
    Guanajuato: ["León", "Guanajuato", "Irapuato"],
    "Nuevo León": ["Monterrey", "Guadalupe", "Apodaca"],
  },
  Spain: {
    Andalusia: ["Seville", "Córdoba", "Málaga", "Granada"],
    Catalonia: ["Barcelona", "Lleida", "Girona"],
    "Madrid": ["Madrid"],
    "Valencia": ["Valencia", "Alicante"],
    "Basque Country": ["Bilbao", "Vitoria-Gasteiz", "San Sebastián"],
  },
  Italy: {
    Lazio: ["Rome", "Latina", "Frosinone"],
    Campania: ["Naples", "Salerno", "Caserta"],
    Lombardy: ["Milan", "Brescia", "Como"],
    Tuscany: ["Florence", "Siena", "Livorno"],
    Sicily: ["Palermo", "Catania", "Messina"],
  },
  China: {
    "Beijing": ["Beijing", "Chaoyang"],
    "Shanghai": ["Shanghai", "Huangpu"],
    "Guangdong": ["Guangzhou", "Shenzhen", "Foshan"],
    "Zhejiang": ["Hangzhou", "Ningbo", "Jiaxing"],
    "Jiangsu": ["Nanjing", "Suzhou", "Wuxi"],
  },
  Russia: {
    Moscow: ["Moscow"],
    "Saint Petersburg": ["Saint Petersburg", "Pushkin"],
    Sverdlovsk: ["Yekaterinburg", "Nizhny Tagil"],
    Novosibirsk: ["Novosibirsk", "Berdsk"],
    "Krasnoyarsk": ["Krasnoyarsk", "Norrilsk"],
  },
  "South Africa": {
    Gauteng: ["Johannesburg", "Pretoria"],
    "Western Cape": ["Cape Town", "Stellenbosch"],
    "KwaZulu-Natal": ["Durban", "Pietermaritzburg"],
    "Eastern Cape": ["Port Elizabeth", "East London"],
  },
  Nigeria: {
    Lagos: ["Lagos", "Abeokuta"],
    Kano: ["Kano", "Katsina"],
    "Federal Capital Territory": ["Abuja", "Garki"],
    Kaduna: ["Kaduna", "Zaria"],
  },
  Egypt: {
    Cairo: ["Cairo", "Giza"],
    Alexandria: ["Alexandria", "Anfushi"],
    Giza: ["Giza"],
  },
  Kenya: {
    Nairobi: ["Nairobi", "Westlands"],
    Mombasa: ["Mombasa", "Bamburi"],
    Kisumu: ["Kisumu", "Ahero"],
    Nakuru: ["Nakuru", "Elburgon"],
  },
  Thailand: {
    Bangkok: ["Bangkok", "Rama"],
    Chiang: ["Chiang Mai", "Chiang Rai"],
    Phuket: ["Phuket"],
  },
  Indonesia: {
    Java: ["Jakarta", "Surabaya", "Bandung"],
    Bali: ["Denpasar"],
    Sumatra: ["Medan", "Palembang"],
  },
  Malaysia: {
    "Kuala Lumpur": ["Kuala Lumpur"],
    Selangor: ["Shah Alam"],
    Penang: ["George Town"],
  },
  Philippines: {
    "Metro Manila": ["Manila", "Quezon City"],
    Cebu: ["Cebu", "Mandaue"],
    Davao: ["Davao"],
  },
  Vietnam: {
    "Ho Chi Minh": ["Ho Chi Minh City", "District 1"],
    Hanoi: ["Hanoi"],
    "Da Nang": ["Da Nang"],
  },
  Singapore: {
    Singapore: ["Singapore"],
  },
  "South Korea": {
    Seoul: ["Seoul", "Gangnam"],
    Busan: ["Busan"],
    Incheon: ["Incheon"],
  },
  "Hong Kong": {
    "Hong Kong": ["Hong Kong", "Central"],
  },
};
